SELECT 
    A.TITLE, 
    A.BOARD_ID, 
    B.REPLY_ID, 
    B.WRITER_ID, 
    B.CONTENTS, 
    DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD AS A LEFT JOIN USED_GOODS_REPLY AS B ON A.BOARD_ID = B.BOARD_ID
WHERE B.CONTENTS IS NOT NULL AND YEAR(A.CREATED_DATE) = 2022 AND MONTH(A.CREATED_DATE) = 10
GROUP BY A.BOARD_ID
ORDER BY B.CREATED_DATE, A.TITLE